<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Handling</title>
</head>
<body>
    <script>
        //Error = am object that is created to represent a problem that occurs
        //        Occur often with user input or establishing a connection

        // try{} = Encloses code that might potentially cause an error
        // catch{} = Catch and handle any thrown Errors from try 
        // finally{} = (optional) Always executes. Used mostly for clean up
        //             ex. close files, close connections, release resources

        
        try{
            console.log("Hello");
        // NETWORK ERRORS
        // PROMISE REJECTION
        // SECURITY ERRORS
        }

        catch(error) {
        console.error(error);
        }


        finally{
        // CLOSE FILES
        // CLOSE CONNECTIONS
        //RELEASE RESOURCES
        console.log("This always executes");
        }
        console.log("You have reached the end!");




        //throwing a new error message

        try{
            const divident = Number(prompt('enter divident'));
            const divisor = Number(promp('enter divisor'));

            if(divisor == 0){
                throw new error('you cant divide by zero');
            }

            if(isNaN(divident)||isNaN(divisor)){
                throw new Error('values must be numbers');
            }

            const result = divident/divisor;
            console.log(result);
        }

        catch(error){
            console.error(error)
        }

        console.log('done');
    </script>
</body>
</html>